#!/bin/bash



# code generated by popular OpenAI agent Chat-GPT, GPTv4.2 and not me




echo "========================================"
echo " Linux Process Management Practical"
echo "========================================"

echo
echo "1. Display running processes using ps"
ps

echo
echo "2. Display system processes using top (5 seconds)"
top -b -n 1

echo
echo "3. Starting a background process (sleep 60)"
sleep 60 &
PID1=$!
echo "Background Process ID: $PID1"

echo
echo "4. Display background jobs"
jobs

echo
echo "5. Changing priority using nice"
nice -n 10 sleep 40 &
PID2=$!
echo "Nice Process ID: $PID2"

echo
echo "6. Display priorities"
ps -o pid,ni,cmd -p $PID2

echo
echo "7. Changing priority using renice"
renice -n 5 -p $PID2

echo
echo "Updated priority:"
ps -o pid,ni,cmd -p $PID2

echo
echo "8. Demonstrating fg command"
echo "------------------------------------------------"
echo "NOTE:"
echo "The fg command works only in an interactive shell."
echo "To test manually:"
echo "  jobs"
echo "  fg %1"
echo "------------------------------------------------"

echo
echo "9. Demonstrating bg command"
echo "------------------------------------------------"
echo "Press Ctrl+Z after running a foreground process,"
echo "then execute:"
echo "  bg"
echo "------------------------------------------------"

echo
echo "10. Waiting for background process to finish"
wait $PID2
echo "Process $PID2 completed."

echo
echo "11. Killing the first background process"
kill $PID1

echo "Killed process $PID1"

echo
echo "Final process list:"
ps

echo
echo "Practical completed successfully."
